server:
  port: 80
logging:
  level:
    cc.au.hkzk: debug
# mybatis
mybatis:
  type-aliases-package: cc.au.hkzk.entity
  # mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

## SqlServer
spring:
    datasource:
      zk:
        jdbc-url: jdbc:sqlserver://localhost:1433;database=zktime606_ID
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        username: sa
        password: SS.9erver
      hk:
        jdbc-url: jdbc:sqlserver://localhost:1433;database=zktime606_ID
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        username: sa
        password: SS.9erver
#      hk:
#        jdbc-url: jdbc:postgresql://localhost:7017/acs_acsdb
#        driver-class-name: org.postgresql.Driver
#        username: postgres
#        password: PostG.9re


